---
- name: Install gitlab on Servers
  hosts: server1
 # become: yes


  tasks:



#       - name: Update cache
 #        apt:
  #         update_cache: yes

   #    - name: Install and configure the necessary dependencies
    #     shell: apt-get install -y curl openssh-server ca-certificates tzdata perl
       
     #  - name: Add the repository to Apt sources
      #   shell: curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | sudo bash
       
       - name: Install Gitlab
       #  shell: sudo GITLAB_ROOT_PASSWORD="yourpassword" EXTERNAL_URL="http://yourIP" apt-get install gitlab-ce
         apt:
           name: gitlab-ce
           state: latest

      # - name: Send hello to Docker
      #   shell: docker run hello-world  
      #   register: results

      # - debug:
       #    msg: "Docker UP"
        # when: "'Hello from Docker!' in results.stdout"
