
---
- name: Install default Apache Web Server
  hosts: servers
  #become: yes


  tasks:

  - name: Check and Print Linux Versions
    debug: var=ansible_os_family

  - block: #======Block for Ubuntu======

       - name: Update cache
         apt:
           update_cache: yes
       - name: Upgrade cache
         apt:
           upgrade: yes

       - name: Install Apache WebServer
         apt:
           pkg: apache2 
           state: latest
       - name: Start Apache and Enable it on the boot
         service: name=apache2 state=started enabled=yes

    when: ansible_os_family == "Debian"

  - block: #======Block for RedHat======

       - debug:
           msg: "Write script install Apache for RedHat"
    when: ansible_os_family == "RedHat"

