
---
- name: Reboot my servers
  hosts: servers
 #become: yes

  tasks:

  - name: Reboot
    shell: sleep 3s && reboot now 
    async: 1
    poll: 0


  - name: Wait untill my servers will come up online
    wait_for:
        host: "{{ inventory_hostname }}"
        state: started
        delay: 5
        timeout: 40
    delegate_to: 127.0.0.1

