---
# tasks file for deploy_apache_web
  - block: #======Block for Ubuntu======

#    - name: Update cache
 #     apt:
  #      update_cache: yes

  #  - name: Upgrade cache
   #   apt:
    #    upgrade: yes

      - name: Install Apache WebServer
        apt:
          pkg: apache2 
          state: latest

      - name: Start Apache and Enable it on the boot
        service: name=apache2 state=started enabled=yes
    when: ansible_os_family == "Debian"

  - block: #======Block for RedHat======
       - debug:
          msg: "Write script install Apache for RedHat"
    when: ansible_os_family == "RedHat"

  - name:  Generate index file
    template:
      src: ./simpl.j2
      dest: "{{folder2}}/index.html"
      mode: 0555
    notify: Restart Apache2

  - name: Copy each file over that matches the given pattern
    ansible.builtin.copy:
      src: "{{item}}"
      dest: "{{folder2}}"
      owner: "root"
      mode: 0644
    with_fileglob:
      - ./*  
